FROM python:3.9.1

#install wget
RUN apt-get install curl wget

# Let's change to  "$NB_USER" command so the image runs as a non root user by default
USER $NB_UID

# ENTRYPOINT ["python" ]
WORKDIR /app

## Copy requirements over into working dir
COPY requirements_sac.txt .

# Install pip and install requirements
RUN pip install --upgrade pip
RUN pip install -r requirements_sac.txt

# Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install

# copy all files into working dir
COPY . .

#using python3 run our agent
CMD [ "python3", "fonpr/sac_agent.py"]