apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: respons-agent
  name: respons-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: respons-agent
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: respons-agent
    spec:
      containers:
      - image: teamrespons/respons_agent:baseline-auto-build
        name: respons-agent
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 8888 
status: {}